name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Install dependencies
      run: |
        uv sync --all-extras
    - name: run bakesite
      run: |
        bakesite bake
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}